defmodule DodoRouter.Agents.ApiCall do
  @moduledoc """
  One call against the agent surface, successful or not.

  Written for every request including the ones that were refused — a denied
  attempt is the row an operator most wants to find, and a log that only
  records successes cannot distinguish "nothing went wrong" from "we have no
  way to tell".
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @outcomes ~w(ok denied error)
  # "rest" is retained for rows written before the REST agent surface was
  # removed. Nothing writes it now, but rejecting it would make old history
  # unreadable — the point of an audit trail is that it survives the code.
  @interfaces ~w(rest mcp)
  # "unauthenticated" covers a call whose credential never resolved, which
  # still deserves a row: repeated ones are someone trying tokens.
  # "agent_token" is likewise historical.
  @principal_kinds ~w(agent_token oauth unauthenticated)

  schema "agent_api_calls" do
    field :principal_kind, :string
    field :principal_name, :string
    field :interface, :string
    field :operation, :string
    field :tool, :string
    field :scopes, {:array, :string}, default: []
    field :target_type, :string
    # A string, not a binary_id: `target_type` already says the id space is
    # not one table's. Sessions are named by the client ("question-7"), so a
    # uuid column dropped every get_session row on the floor.
    field :target_id, :string
    field :outcome, :string
    field :http_status, :integer
    field :error, :string
    field :returned_bodies, :boolean, default: false
    field :remote_ip, :string
    field :user_agent, :string
    field :duration_ms, :integer

    belongs_to :user, DodoRouter.Accounts.User
    belongs_to :router, DodoRouter.Routers.Router

    # `timestamps`, not a bare `field :inserted_at` — a plain field is not
    # autogenerated, and every insert fails the NOT NULL constraint. Which is
    # how this shipped green: the rescue in Agents.record_call/1 turned a
    # 100%-failed audit into a log line no test was reading.
    timestamps(type: :utc_datetime_usec, updated_at: false)
  end

  def changeset(call, attrs) do
    call
    |> cast(attrs, [
      :user_id,
      :router_id,
      :principal_kind,
      :principal_name,
      :interface,
      :operation,
      :tool,
      :scopes,
      :target_type,
      :target_id,
      :outcome,
      :http_status,
      :error,
      :returned_bodies,
      :remote_ip,
      :user_agent,
      :duration_ms
    ])
    |> validate_required([:principal_kind, :interface, :operation, :outcome])
    |> validate_inclusion(:principal_kind, @principal_kinds)
    |> validate_inclusion(:interface, @interfaces)
    |> validate_inclusion(:outcome, @outcomes)
    # Truncated rather than rejected: an oversized user-agent must not be the
    # reason a call goes unrecorded.
    |> update_change(:error, &truncate(&1, 2_000))
    |> update_change(:user_agent, &truncate(&1, 500))
    # These are varchar(255). Losing the whole record because a caller passed
    # something long is the worst possible failure for an audit table — the row
    # exists to say a call happened, and a truncated field still says that.
    |> update_change(:operation, &truncate(&1, 250))
    |> update_change(:principal_name, &truncate(&1, 250))
    |> update_change(:tool, &truncate(&1, 250))
    # `target_id` is text rather than varchar, so nothing rejects it — but a
    # session id is client-supplied and unbounded, and an audit row is not
    # where a caller's megabyte belongs.
    |> update_change(:target_id, &truncate(&1, 250))
  end

  def outcomes, do: @outcomes

  defp truncate(nil, _max), do: nil

  defp truncate(value, max) when is_binary(value) do
    if String.length(value) <= max, do: value, else: String.slice(value, 0, max) <> "…"
  end
end
