import Config

# Set by scripts/dev-workspace.sh in each jj workspace's .envrc, so several
# branches can run at once without sharing a database, a port, or — because
# cookies are not scoped by port — a session cookie.
workspace_suffix =
  case System.get_env("DODO_WORKSPACE", "") do
    "" -> ""
    name -> "_" <> String.replace(name, "-", "_")
  end

# Configure your database
config :dodo_router, DodoRouter.Repo,
  username: System.get_env("DB_USERNAME", "postgres"),
  password: System.get_env("DB_PASSWORD", "postgres"),
  hostname: System.get_env("DB_HOSTNAME", "localhost"),
  database: System.get_env("DB_NAME", "dodo_router_dev"),
  port: String.to_integer(System.get_env("DB_PORT", "5432")),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("DB_POOL_SIZE", "10"))

config :dodo_router, :cookie_suffix, workspace_suffix

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :dodo_router, DodoRouterWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  # attesto requires an https issuer (RFC 8414 §2), so the OAuth/MCP flow needs
  # TLS even locally. Generated once by `mix attesto_phoenix.gen.dev_https`,
  # which shells out to mkcert so the cert is trusted with no tunnel.
  #
  # Inlined rather than `AttestoPhoenix.DevTLS.https_opts(port: 4443)`: config
  # files are evaluated before dependencies are loaded, so calling into one
  # raises UndefinedFunctionError. This is that function's output verbatim.
  https: [
    port: 4443,
    cipher_suite: :strong,
    certfile: Path.expand("priv/cert/localhost.pem", File.cwd!()),
    keyfile: Path.expand("priv/cert/localhost-key.pem", File.cwd!()),
    # Bandit caps a single header near 10KB; a JWT access token plus a DPoP
    # proof goes past that and 431s underfoot.
    http_1_options: [max_header_length: 65_536]
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IxHdHG0PMgAoc4WIcqNwjorMu7LzJKBl6UHI4WmwPCqK8Xw+baxD3Gao5Iwa1eed",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:dodo_router, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:dodo_router, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :dodo_router, DodoRouterWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/dodo_router_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# The app is reachable on both listeners in dev: plain http for the dashboard,
# TLS for the OAuth/MCP flow (attesto requires an https issuer). Both are
# legitimate origins for the MCP endpoint's DNS-rebinding check.
config :dodo_router, :mcp_allowed_origins, ["https://localhost:4443"]

# Enable dev routes for dashboard and mailbox
config :dodo_router, dev_routes: true
config :dodo_router, :env, :dev

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# The authorization server in development.
#
# Both `issuer` and `audience` must be https — attesto rejects http outright,
# with no localhost exemption — so local development needs a trusted cert even
# though `require_https: false` means incoming requests themselves may be plain.
#
# One-time setup:
#     brew install mkcert && mkcert -install
#     mix attesto_phoenix.gen.dev_https
#
# then run the server with the https endpoint on 4443. Until then the OAuth
# endpoints will not boot, but the rest of the app is unaffected.
config :dodo_router, AttestoPhoenix.Config,
  require_https: false,
  issuer: System.get_env("ATTESTO_ISSUER") || "https://localhost:4443",
  audience: (System.get_env("ATTESTO_ISSUER") || "https://localhost:4443") <> "/mcp"
