defmodule DodoRouterWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dodo_router
  require Logger

  @cookie_suffix Application.compile_env(:dodo_router, :cookie_suffix, "")

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dodo_router_key" <> @cookie_suffix,
    signing_salt: "IPNBAiLl",
    same_site: "Lax"
  ]

  if Application.compile_env(:dodo_router, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dodo_router,
    gzip: not code_reloading?,
    only: DodoRouterWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dodo_router
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug :quiet_health_checks
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Must run before Plug.Parsers: signature verification needs the raw body.
  plug Stripe.WebhookPlug,
    at: "/webhooks/stripe",
    handler: DodoRouterWeb.StripeWebhookHandler,
    secret: {DodoRouter.Billing, :webhook_secret, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # Proxy requests carry base64 images (Claude Code screenshots etc.) and
    # easily exceed Plug's 8MB default; Anthropic itself accepts up to ~32MB.
    length: 50_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DodoRouterWeb.Router

  defp quiet_health_checks(%{request_path: "/health"} = conn, _opts) do
    Logger.disable(self())
    conn
  end

  defp quiet_health_checks(conn, _opts), do: conn
end
