defmodule DodoRouter.AuthZ.ConsentPolicy do
  @moduledoc """
  Host implementation of `AttestoPhoenix.ConsentPolicy`.

  Generated by `mix attesto_phoenix.install`. Each callback below is a stub
  that raises until you implement it. See `AttestoPhoenix.ConsentPolicy` for the
  full contract (with the governing RFC per callback) and wire these
  functions in `config/config.exs` under `config :your_app,
  AttestoPhoenix.Config` (the installer wired the default function names for
  you).
  """

  @behaviour AttestoPhoenix.ConsentPolicy

  @impl true
  def authenticate_resource_owner(_arg1, _arg2, _arg3) do
    raise "implement authenticate_resource_owner/3 (generated by mix attesto_phoenix.install)"
  end

  @impl true
  def consent(_arg1, _arg2, _arg3) do
    raise "implement consent/3 (generated by mix attesto_phoenix.install)"
  end
end
